core/urls.py
from django.urls import path #type: ignore
from .views import *
from products.views import create_order

app_name = 'core'

urlpatterns = [
    path('', pos, name="home"),
    path('orders/', order_history, name="order-history"),

    #APIs
    path("api/products/", products_api, name="products_api"),
    path("api/orders/", create_order, name="create_order"),

    #Orders
    path("orders/", order_history, name="order_history"),
    path("orders/<int:order_id>/update-status/", update_order_status, name="update_order_status"),
]

flavor/urls.py
from django.contrib import admin #type:ignore
from django.urls import path, include #type:ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('userauth.urls'))
]

userauth/urls.py
from django.urls import path
from .views import login_view, logout_view

app_name = 'userauth'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name='logout'),
]

core/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models #type:ignore
from cloudinary.models import CloudinaryField #type:ignore
from userauth.models import User 

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title
    
STATUS = (
    ("draft","Draft"),
    ("published","Published"),
)
    
class Product(models.Model):
    title = models.CharField(max_length=20)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
    image  = CloudinaryField('image', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0.00)
    product_status = models.CharField(choices=STATUS, max_length=10, default="draft")
    qty = models.IntegerField()
    order_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products"

    def __str__(self):
        return self.title

PAYMENT = (
    ("Cash", "CASH"),
    ("Mpesa", "M-PESA"),
)

class Order(models.Model):
    order_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    customer = models.CharField(max_length=100, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    totalcost = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    mode_payment = models.CharField(choices=PAYMENT, max_length=20, default="Mpesa")
    code = models.CharField(max_length=50, blank=True, null=True)
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Orders"

    def __str__(self):
        return f"Order {self.id} - {self.customer}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey("product", on_delete=models.SET_NULL, null=True)
    qty = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.product} (x{self.qty})"

userauth/models.py
from django.db import models #type: ignore
from django.contrib.auth.models import AbstractUser #type: ignore
from cloudinary.models import CloudinaryField #type:ignore

# Create your models here.
class StaffRole(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=20, blank=True, null=True)
    icon = CloudinaryField('image', blank=True, null=True)


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=200)
    bio = models.TextField()
    role = models.ForeignKey(StaffRole, on_delete=models.SET_NULL, null=True, related_name="StaffRole")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

core/views.py
from django.shortcuts import get_object_or_404, render #type: ignore
from django.http import JsonResponse 
from django.views.decorators.http import require_POST
from products.models import Product, Order
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
@login_required
def pos(request):
    if request.htmx:
        return render(request, 'partials/products.html')
    return render(request, 'views/pos.html')

def products_api(request):
    products = Product.objects.filter(product_status="published")
    data = [
        {
            "id": p.id,
            "title": p.title,
            "category": getattr(p.category, "title", None),
            "image": getattr(p.image, "url", ""),
            "price": str(p.price),
            "qty": p.qty,
        }
        for p in products
    ]
    return JsonResponse(data, safe=False)

def order_history(request):
    # filtering
    status = request.GET.get("status", "all")  # "paid", "unpaid", or "all"
    orders = Order.objects.all().order_by("-order_date")

    if status == "paid":
        orders = orders.filter(paid_status=True)
    elif status == "unpaid":
        orders = orders.filter(paid_status=False)

    # pagination
    paginator = Paginator(orders, 20)  # 20 per page
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        "status": status,
    }

    if request.htmx:
        return render(request, "partials/order-table.html", context)

    return render(request, "views/orders.html", context)

@require_POST
def update_order_status(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    # Convert the string to a boolean
    paid_status = request.POST.get("paid_status")
    order.paid_status = True if paid_status == "true" else False
    order.save(update_fields=["paid_status"])

    # Return just the updated row partial
    return render(request, "partials/order-row.html", {"order": order})

products/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from .models import Order, OrderItem, Product

# Create your views here.
@csrf_exempt
def create_order(request):
    if request.method == "POST":
        data = json.loads(request.body)
        customer = data.get("customer")
        comment = data.get("comment")
        payment = data.get("payment")
        total = data.get("total")
        items = data.get("items", [])
        user = request.user if request.user.is_authenticated else None

        # Create main order
        order = Order.objects.create(
            order_by=user,
            customer=customer,
            comment=comment,
            totalcost=total,
            mode_payment=payment,
        )

        # Create order items
        for i in items:
            prod = Product.objects.get(id=i["product"])
            OrderItem.objects.create(
                order=order,
                product=prod,
                qty=i["qty"],
                price=i["price"],
            )

        return JsonResponse(
            {"message": "Order placed successfully", "order_id": order.id}, status=201
        )

    return JsonResponse({"error": "Invalid request"}, status=400)

userauth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from django.core.mail import EmailMessage
from django.utils import timezone
from django.urls import reverse
from .models import User

# Create your views here.
def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "Successfully logged in")
            return redirect('core:home')
        else:
            messages.error(request, "Invalid login credentials")
            return redirect('userauth:login')
    return render(request, 'views/login.html')

def logout_view(request):
    logout(request)
    return redirect('userauth:login')

templates/base.html
{% load static %}
{% load django_htmx %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flavor Haven - {% block title %}{% endblock title %}</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'src/main.css' %}">

    <!-- JS -->
    <script defer src="{% static 'js/alpine.js' %}" ></script>
    <script src="{% static 'js/store.js' %}" ></script>
    <script src="{% static 'js/htmx.js' %}" ></script>

    <!-- bootstrap -->
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% htmx_script %}

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css" rel="stylesheet" type="text/css">

</head>
<body>
    {% include 'includes/header.html' %}
    <!-- Messages -->
    <div class="position-fixed top-0 start-0 p-3" style="z-index:1055; max-width:350px;">
        {% if messages %}
            {% for message in messages %}
                <div 
                    x-data="{ show: true }" 
                    x-show="show"
                    x-transition:enter="transform transition ease-out duration-500"
                    x-transition:enter-start="-translate-x-full opacity-0"
                    x-transition:enter-end="translate-x-0 opacity-100"
                    x-transition:leave="transform transition ease-in duration-500"
                    x-transition:leave-start="translate-x-0 opacity-100"
                    x-transition:leave-end="translate-x-full opacity-0"
                    x-init="setTimeout(() => show = false, 7000)"
                    class="card shadow border-0 mb-2"
                >
                    <div class="card-body d-flex align-items-center justify-content-between">
                        <!-- Left: message -->
                        <div class="d-flex align-items-center gap-2">
                            {% if message.tags == 'success' %}
                                <span class="text-success">✔</span>
                            {% elif message.tags == 'error' %}
                                <span class="text-danger">✖</span>
                            {% else %}
                                <span class="text-primary">ℹ</span>
                            {% endif %}
                            <span class="fw-semibold">{{ message }}</span>
                        </div>

                        <!-- Right: close -->
                        <button 
                            type="button" 
                            class="border-0 bg-transparent fw-bold text-muted ms-2" 
                            @click="show = false"
                        >×</button>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <!-- End Messages -->
    <main id="content" class="container px-1">
        {% block content %}{% endblock %}
    </main> 
    <form style="display:none;">
        {% csrf_token %}
    </form>
    <script>
        document.body.addEventListener("htmx:configRequest", (event) => {
            const csrfToken = document.querySelector("[name=csrfmiddlewaretoken]")?.value;
            if (csrfToken) {
            event.detail.headers["X-CSRFToken"] = csrfToken;
            }
        });
    </script>   
</body>
</html>

templates/includes/header.html
{% load static %}
<div class="justify-content-center align-items-center d-flex my-4 sticky-top z-5">
    <div class="d-flex justify-content-center align-items-center shadow-sm rounded-5 gap-5 py-3 px-4 border bg-white">
        <div>
            <a hx-get="{% url 'core:home' %}" hx-target="#content" hx-push-url="true"><img src="{% static 'images/flavor.png' %}" width="55" alt=""></a>
        </div>
        
        <div>
            <button class="border-0 bg-white position-relative"  
                    data-bs-toggle="offcanvas" 
                    data-bs-target="#offcanvasRight" 
                    aria-controls="offcanvasRight">
                <img src="{% static 'images/cart.png' %}" alt="Cart" width="35">

                <!-- Cart item count badge -->
                <span
                    class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                    x-data
                    x-text="$store.cart.count"
                ></span>
            </button>

            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title fw-bold fs-2" id="offcanvasRightLabel">Place The Order</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>

                <div class="offcanvas-body" x-data>
                <template x-if="$store.cart.items.length === 0">
                    <p class="text-muted">Your cart is empty.</p>
                </template>

                <template x-for="item in $store.cart.items" :key="item.id">
                    <div class="d-flex justify-content-between align-items-center mb-3 border shadow p-2 rounded-2">
                    <div>
                        <h6 x-text="item.title" class="fw-bold fs-4"></h6>
                        <small>Ksh. <span x-text="item.price"></span></small>
                        <div class="d-flex gap-5 align-items-center mt-1">
                        <button @click="$store.cart.decrement(item.id)" class="btn btn-sm btn-outline-danger">-</button>
                        <span class="mx-2 fw-bold" x-text="item.quantity"></span>
                        <button @click="$store.cart.increment(item.id)" class="btn btn-sm btn-outline-success">+</button>
                        </div>
                    </div>
                    <button @click="$store.cart.remove(item.id)" class="btn btn-sm btn-outline-dark">x</button>
                    </div>
                </template>

                <!-- Cart total -->
                <div class="mt-3 border-top pt-3">
                    <h5>Total: Ksh. <span x-text="$store.cart.total"></span></h5>
                </div>

                <!-- Order Form -->
                <div class="mt-3">
                    <input type="text" class="form-control mb-2"
                        placeholder="Customer name"
                        x-model="$store.cart.customer">

                    <textarea class="form-control mb-2"
                            placeholder="Comment"
                            x-model="$store.cart.comment"></textarea>

                    <select class="form-select mb-3" x-model="$store.cart.payment">
                        <option value="Mpesa">Mpesa</option>
                        <option value="Cash">Cash</option>
                    </select>

                    <button class="btn btn-success w-100"
                            @click="$store.cart.placeOrder()"
                            :disabled="!$store.cart.items.length">
                    Place Order
                    </button>
                </div>
                </div>
            </div>
        </div>


        <div>
            <a hx-get="{% url 'core:order-history' %}" hx-target="#content" hx-push-url="true"><img src="{% static 'images/orders.png' %}" width="35" alt=""></a>
        </div>
        
        <div>
            
            <div class="dropdown ">
                <button class="border-0 bg-transparent" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <a href="#"><img src="{% static 'images/user-profile.png' %}" width="40" alt=""></a>
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">My Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'userauth:logout' %}">Log out</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/order-row.html
<tr id="order-{{ order.id }}">
    <td>{{ order.id }}</td>
    <td>{{ order.customer }}</td>
    <td>{{ order.totalcost }}</td>
    <td>
        <select 
            hx-post="{% url 'core:update_order_status' order.id %}" 
            hx-target="#order-{{ order.id }}" 
            hx-swap="outerHTML"
            name="paid_status"
            class="form-select form-select-sm"
            hx-trigger="change"
        >
            <option value="false" {% if not order.paid_status %}selected{% endif %}>Unpaid</option>
            <option value="true" {% if order.paid_status %}selected{% endif %}>Paid</option>
        </select>
    </td>
    <td>
        <button 
            type="button" 
            class="btn btn-sm btn-outline-danger" 
            data-bs-toggle="modal" 
            data-bs-target="#orderModal{{ order.id }}">
            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4.03 6-9 6s-9-4.8-9-6c0-1.2 4.03-6 9-6s9 4.8 9 6Z"/>
                <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
            </svg>
        </button>
    </td>
</tr>

<!-- Modal -->
<div class="modal fade" id="orderModal{{ order.id }}" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      
      <div class="modal-header">
        <h5 class="modal-title">Order #{{ order.id }} - {{ order.customer }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <div class="modal-body">
        <p><strong>Total:</strong> Ksh. {{ order.totalcost }}</p>
        <p><strong>Payment Mode:</strong> {{ order.mode_payment }}</p>
        <p><strong>Status:</strong> 
          {% if order.paid_status %}
            <span class="badge bg-success">Paid</span>
          {% else %}
            <span class="badge bg-danger">Unpaid</span>
          {% endif %}
        </p>

        <hr>
        <h6>Items</h6>
        <ul class="list-group">
          {% for item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              {{ item.product.title }}
              <span class="badge bg-secondary">{{ item.qty }} × Ksh.{{ item.price }}</span>
            </li>
          {% endfor %}
        </ul>

        {% if order.comment %}
          <hr>
          <p><strong>Comment:</strong> {{ order.comment }}</p>
        {% endif %}
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
      
    </div>
  </div>
</div>

templates/partials/order-table.html
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Customer</th>
      <th>Total</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for order in page_obj %}
      {% include "partials/order-row.html" with order=order %}
    {% empty %}
      <tr><td colspan="5" class="text-center">No orders found.</td></tr>
    {% endfor %}
  </tbody>
</table>

<!-- Pagination -->
<nav aria-label="Orders pagination">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" hx-get="?page={{ page_obj.previous_page_number }}&status={{ status }}" hx-target="#orders-table" hx-swap="innerHTML">&laquo;</a>
      </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      <li class="page-item {% if num == page_obj.number %}active{% endif %}">
        <a class="page-link" hx-get="?page={{ num }}&status={{ status }}" hx-target="#orders-table" hx-swap="innerHTML">{{ num }}</a>
      </li>
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" hx-get="?page={{ page_obj.next_page_number }}&status={{ status }}" hx-target="#orders-table" hx-swap="innerHTML">&raquo;</a>
      </li>
    {% endif %}
  </ul>
</nav>
<div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer</th>
                <th>Total</th>
                <th>Paid status</th>
                <th>View</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                {% include "partials/order-row.html" %}
            {% endfor %}
        </tbody>
    </table>
</div>

templates/partials/products.html
<div x-data>
  <h2 class="fw-bold text-center mb-4">All Products</h2>

  <!-- CATEGORY FILTERS -->
  <div class="container mb-3">
    <div class="d-flex flex-wrap justify-content-center gap-2">
      <!-- "All" button -->
      <button 
        class="btn btn-sm" 
        :class="$store.products.selectedCategory === '' ? 'btn-danger' : 'btn-outline-danger'"
        @click="$store.products.selectedCategory = ''"
      >All</button>

      <!-- Dynamic categories -->
      <template x-for="cat in $store.products.categories" :key="cat">
        <button 
          class="btn btn-sm"
          :class="$store.products.selectedCategory === cat ? 'btn-danger' : 'btn-outline-danger'"
          @click="$store.products.selectedCategory = cat"
          x-text="cat"
        ></button>
      </template>
    </div>
  </div>

  <!-- SEARCH BAR -->
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <div class="input-group mb-3">
          <input 
            type="text" 
            class="form-control" 
            placeholder="Searching for.." 
            aria-label="Search input" 
            x-model.debounce.300ms="$store.products.searchTerm"
          >
        </div>
      </div>
    </div>
  </div>

  <!-- PRODUCTS LIST -->
  <div class="container">
    <div class="row justify-content-center p-2" x-init="$store.products.fetch()">
      <template x-if="$store.products.filtered.length === 0">
        <p class="text-center text-muted">No products found.</p>
      </template>

      <template x-for="product in $store.products.filtered" :key="product.id">
        <div class="col-6 col-sm-6 col-md-3 col-lg-2 mb-4">
          <div class="card h-100 shadow border-0" x-data>
            <img
              :src="product.image"
              class="card-img-top"
              :alt="product.title"
              style="height: 180px; object-fit: cover;"
            >

            <div class="card-body text-center">
              <h5 class="card-title" x-text="product.title"></h5>
              <p>Ksh. <span x-text="product.price"></span></p>

              <!-- Add to Cart (only when qty == 0) -->
              <template x-if="$store.cart.getQty(product.id) === 0">
                <button
                  @click="$store.cart.add(product)"
                  class="btn btn-danger w-100"
                >
                  Add to Cart
                </button>
              </template>

              <!-- Quantity controls (only when qty > 0) -->
              <template x-if="$store.cart.getQty(product.id) > 0">
                <div class="d-flex justify-content-between align-items-center">
                  <button
                    @click="$store.cart.decrement(product.id)"
                    class="btn btn-outline-danger"
                  >-</button>

                  <span class="fw-bold" x-text="$store.cart.getQty(product.id)"></span>

                  <button
                    @click="$store.cart.increment(product.id)"
                    class="btn btn-outline-success"
                  >+</button>
                </div>
              </template>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</div>

templates/views/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome - Login In</title>

    <!-- styles -->
    <link rel="stylesheet" href="{% static 'src/login.css' %}">

    <!-- bootstrap -->
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- ALpine -->
    <script defer src="{% static 'js/alpine.js' %}" ></script>
</head>
<body>

    <div class="container vh-100 d-flex justify-content-center align-items-center">
        <div class="row">
            <div class="align-items-center justify-content-center d-flex my-5">
                <img src="{% static 'images/flavor.png' %}" width="200" alt="">
            </div>
            <!-- Messages -->
            <div class="position-fixed top-0 start-0 p-3" style="z-index:1055; max-width:350px;">
                {% if messages %}
                    {% for message in messages %}
                        <div 
                            x-data="{ show: true }" 
                            x-show="show"
                            x-transition:enter="transform transition ease-out duration-500"
                            x-transition:enter-start="-translate-x-full opacity-0"
                            x-transition:enter-end="translate-x-0 opacity-100"
                            x-transition:leave="transform transition ease-in duration-500"
                            x-transition:leave-start="translate-x-0 opacity-100"
                            x-transition:leave-end="translate-x-full opacity-0"
                            x-init="setTimeout(() => show = false, 7000)"
                            class="card shadow border-0 mb-2"
                        >
                            <div class="card-body d-flex align-items-center gap-4 justify-content-between">
                                <!-- Left: message -->
                                <div class="d-flex align-items-center gap-2 w-100">
                                    {% if message.tags == 'success' %}
                                        <span class="text-success">✔</span>
                                    {% elif message.tags == 'error' %}
                                        <span class="text-danger">✖</span>
                                    {% else %}
                                        <span class="text-primary">ℹ</span>
                                    {% endif %}
                                    <span class="fw-semibold">{{ message }}</span>
                                </div>

                                <!-- Right: close -->
                                <div
                                    type="button" 
                                    class="close border-0 bg-transparent fw-bold text-muted ms-2" 
                                    @click="show = false"
                                >×</div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <!-- End Messages -->
            <div class="align-items-center justify-content-center d-flex">
                <form class="form" method="post">
                    {% csrf_token %}
                    <input type="text" class="input" placeholder="Enter Email" name="username" required>
                    <input type="password" class="input" placeholder="*********" required name="password">
                    <button type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/views/orders.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center align-items-center my-5">
  <div>
    <a href="?status=all" class="btn btn-sm {% if status == 'all' %}btn-primary{% else %}btn-outline-primary{% endif %}">All</a>
    <a href="?status=paid" class="btn btn-sm {% if status == 'paid' %}btn-success{% else %}btn-outline-success{% endif %}">Paid</a>
    <a href="?status=unpaid" class="btn btn-sm {% if status == 'unpaid' %}btn-danger{% else %}btn-outline-danger{% endif %}">Unpaid</a>
  </div>
</div>

<div id="orders-table" hx-get="{% url 'core:order_history' %}?status={{ status }}" hx-trigger="load" hx-target="#orders-table" hx-swap="innerHTML">
  {% include 'partials/order-table.html' %}
</div>
{% endblock content %}

templates/views/pos.html
{% extends 'base.html' %}

{% block content %}
{% include 'partials/products.html' %}
{% endblock content %}